name: Playwright github action e2e test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  PlaywrightTest:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checks out the source code from the main repository
      uses: actions/checkout@v3

    - name: Sets up the Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
   
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test

    - name: Show pass fali number
      run: |
        FILE_PATH=test-result.txt
        if [ -f "$FILE_PATH" ]; then
          # Read the contents of the file
          DATA=$(cat "$FILE_PATH")
          echo "Content of data.txt: $DATA"
        else
          echo "File not found: $FILE_PATH"
          exit 1
        fi

    - name: Read content from text file
      id: read-content
      run: echo "::set-output name=file-content::$(<test-result.txt)"
    
    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp-relay.brevo.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: Shahin.Shanaous@brainstation-23.com
        to: mshanaousrabby01@gmail.com
        subject: GitHub Action Notification
        body: |
          The GitHub Actions workflow has completed successfully.The test result is: 
          ${{ steps.read-content.outputs.file-content }}
  
          Commit SHA: ${{ github.sha }}
          Commit Message: ${{ github.event.head_commit.message }}
            
    env:
      TZ: 'UTC'
  