name: Playwright github action e2e test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  PlaywrightTest:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checks out the source code from the main repository
      uses: actions/checkout@v3

    - name: Sets up the Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
   
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test

    - name: Show pass fali number
      run: |
        FILE_PATH=test-result.txt
        if [ -f "$FILE_PATH" ]; then
          # Read the contents of the file
          DATA=$(cat "$FILE_PATH")
          echo "Content of data.txt: $DATA"
        else
          echo "File not found: $FILE_PATH"
          exit 1
        fi
      
